$ANSIBLE_VAULT;1.1;AES256
65396631626133386364636330383038303634363466616463613833653562363835376238373331
3336336263626238646235633863663665643365393066610a313863623730613631363866623966
30656430326230646633623430393466393737336266363630386263373035646339323961393637
3465393034303339630a393565613437373436363033353161333465326566653165373863313839
30323432643663336636646132643532653539393635643136313065643766663434326237386263
34636136373861373234306165376634663137636363663064333864376230323136386539326365
30616564323033633931363535366439323134386466383837363264366430616461323565333365
34396366616631336534616135663266313231393532313639373931653339356264363337353330
36343633633936316430306232386532336336623636643365393266343464316463623930343836
6536323635653530343230373466626163646562653361616663
